server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureke/
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://localhost:8081/
          predicates:
            - Path=/api/login
        - id: reservation
          uri: http://localhost:8082/
          predicates:
            - Path=/api/reservation/**
