
server:
  port: 8761

eureka:
  instance:
    hostname: 3.38.45.239
    client:
      registerWithEureka: false
      fetchRegistry: false
    server:
      serverUrl:
        defaultZone: http://3.38.45.239/eureka/